# Generated by Django 4.2.1 on 2023-05-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(to='Blog.categorias'),
        ),
    ]
