# Generated by Django 4.2.1 on 2023-06-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='categorias',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='update',
            new_name='updated',
        ),
    ]
